<?php

namespace ProduitBundle\Repository;

/**
 * WhishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhishlistRepository extends \Doctrine\ORM\EntityRepository
{
}
