main_user:
    resource: "@MainBundle/Resources/config/routing/user.yml"
    prefix:   /user

main_homepage:
    path:     /Index
    defaults: { _controller: MainBundle:Default:index }

main_homepageback:
    path:     /IndexBack
    defaults: { _controller: MainBundle:Default:indexBack }

whishlist_new:
    path:     /{id}/new
    defaults: { _controller: "ProduitBundle:Whishlist:new" }
    methods:  [GET, POST]
test:
    path:     /Indextest
    defaults: { _controller: MainBundle:Default:indextest }
ddashboard:
    path:     /datadashboard
    defaults: { _controller: "MainBundle:Default:datadashboard" }
    methods:  GET