<?php

namespace ProduitBundle\Repository;

/**
 * ComProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
