presentation:
  path:  /produit/{id}
  defaults: { _controller: EcommerceBundle:Produits:presentation }

categorieProduits:
  path:  /categorie/{categorie}
  defaults: { _controller: EcommerceBundle:Produits:categorie }

rechercheProduits:
  path:  /recherche
  defaults: { _controller: EcommerceBundle:Produits:rechercheTraitement }
produits:
  path:  /
  defaults: { _controller: EcommerceBundle:Produits:produits }
render:
  path:  /render
  defaults: { _controller: EcommerceBundle:Produits:render }