reclamation_index:
    path:     /
    defaults: { _controller: "ReclamationBundle:Reclamation:index" }
    methods:  GET

reclamation_home:
    path:     /home
    defaults: { _controller: "ReclamationBundle:Reclamation:home" }
    methods:  GET

reclamation_show:
    path:     /{id}/show
    defaults: { _controller: "ReclamationBundle:Reclamation:show" }
    methods:  GET

reclamation_own:
    path:     /own
    defaults: { _controller: "ReclamationBundle:Reclamation:own" }
    methods:  GET


reclamation_new:
    path:     /new
    defaults: { _controller: "ReclamationBundle:Reclamation:new" }
    methods:  [GET, POST]

reclamation_edit:
    path:     /{id}/edit
    defaults: { _controller: "ReclamationBundle:Reclamation:edit" }
    methods:  [GET, POST]

reclamation_delete:
    path:     /{id}/delete
    defaults: { _controller: "ReclamationBundle:Reclamation:delete" }
    methods:  DELETE
reclamation_del:
    path:     /{id}/del
    defaults: { _controller: "ReclamationBundle:Reclamation:deletebyid" }
reclamation_etatacc:
    path:     /{id}/etatacc
    defaults: { _controller: "ReclamationBundle:Reclamation:etatacc" }
    methods:  [GET, POST]
reclamation_etatrej:
    path:     /{id}/etatrej
    defaults: { _controller: "ReclamationBundle:Reclamation:etatrej" }
    methods:  [GET, POST]