<?php

namespace ProduitBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function  searchPrixCroissant(){
        $query=$this->getEntityManager()
            ->createQuery("SELECT p FROM ProduitBundle:Produit p order by p.prix");
        return $query->getResult();
    }
    public function  searchPrixDecroissant(){
        $query=$this->getEntityManager()
            ->createQuery("SELECT p FROM ProduitBundle:Produit p order by p.prix desc");
        return $query->getResult();
    }
    public function  searchName(){
        $query=$this->getEntityManager()
            ->createQuery("SELECT p FROM ProduitBundle:Produit p order by p.nom");
        return $query->getResult();
    }
    public function  searchPromo(){
        $query=$this->getEntityManager()
            ->createQuery("SELECT p FROM ProduitBundle:Produit p where p.etatPromo=1");
        return $query->getResult();
    }
    public function listeWish()
    {
        $query = $this->getEntityManager()

            ->createQuery(' SELECT u FROM  ProduitBundle:Produit u  JOIN  ProduitBundle:Whishlist b where u.id =: b.idProduit  ');
        return $query->getResult();
    }
    public function mefind($name){
        $query=$this->getEntityManager()
            ->createQuery("select m from ProduitBundle:Produit m where m.nom like :name ");
        $query->setParameter(":name",'%'.$name.'%');
        return $query->getResult();
    }
}
