read:
  path:     /read
  defaults: { _controller: "ForumBundle:commentaire:read" }

update_page:
  path:     /update/{id}
  defaults: { _controller: "ForumBundle:commentaire:edit" }

delete_page:
  path:     /delete/{id}
  defaults: { _controller: "ForumBundle:commentaire:delete" }
