<?php

namespace ProduitBundle\Repository;

/**
 * WhishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhishlistRepository extends \Doctrine\ORM\EntityRepository
{
    public function listeWish($user)
    {


        $query=$this->getEntityManager()->createQuery("SELECT u FROM ProduitBundle:Produit u JOIN 
        ProduitBundle:Whishlist b Where b.idClient= :user");
        $query->setParameter('user',$user);
        return $query->getResult();
    }
}
