<?php

namespace EspeceBundle\Repository;

/**
 * saisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saisonRepository extends \Doctrine\ORM\EntityRepository
{
}
