<?php

namespace EspeceBundle\Repository;

/**
 * especeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class especeRepository extends \Doctrine\ORM\EntityRepository
{
}
