user_index:
    path:     /
    defaults: { _controller: "MainBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:User:show" }
    methods:  GET

user_ChangeEtat:
    path:     /{id}/change
    defaults: { _controller: "MainBundle:User:changeEtat" }
    methods:  GET


