routingPanier:
    resource: "@EcommerceBundle/Resources/config/routing/routingPanier.yml"
    prefix:   /panier
routingProduits:
    resource: "@EcommerceBundle/Resources/config/routing/routingProduits.yml"
    prefix:   /
routingCommandes:
    resource: "@EcommerceBundle/Resources/config/routing/routingCommandes.yml"
    prefix: /
factures:
    path:    /profile/factures
    defaults: { _controller: EcommerceBundle:Utilisateurs:factures }

facturePDF:
    path:    /profile/factures/PDF/{id}
    defaults: { _controller: EcommerceBundle:Utilisateurs:facturePDF }