<?php

namespace ForumBundle\Repository;

/**
 * commentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentaireRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByid($id)
    {

        return $this->getEntityManager()
            ->createQuery("SELECT p FROM ForumBundle:publication p WHERE p.id =:id")
            ->setParameter('id',$id)
            ->getOneOrNullResult();

    }
}
