<?php

namespace EspeceBundle\Repository;

/**
 * especeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class especeRepository extends \Doctrine\ORM\EntityRepository
{
    public function mefind($name){
        $query=$this->getEntityManager()
            ->createQuery("select m from EspeceBundle:Espece m where m.nomEspece like :name ");
        $query->setParameter(":name",'%'.$name.'%');
        return $query->getResult();
    }
}
