package com.mycompany.myapp;


import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.mycompany.gui.FrontDisplayForm;
import com.mycompany.gui.HomeForm;
import com.mycompany.gui.HomeFormSKA;
import java.util.ArrayList;
import com.mycompany.entities.Produit;
import com.mycompany.entities.Utilisateurs;
import com.mycompany.gui.Adreesse;
import com.mycompany.gui.AddAdresse;
import com.mycompany.gui.Panier;
import com.mycompany.utils.DB;
import com.mycompany.services.SrProduct;
/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;
    
     public static Utilisateurs user;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
      public static ArrayList<Produit> listeprod;


    public void start() {
        
         listeprod = new ArrayList<Produit>();
       //  Produit p1 = new Produit("sicam", 500, "mnayek asl", 1, "3asba");
        Produit p3 = new Produit(4);
        Produit p4 =new Produit(5, "LENOOOOVOOOO", 10 , 1000);

        listeprod.add(p4);
       // listeprod.add(p2);
        SrProduct sr = new SrProduct();
        sr.addToPanier(p4);
        
        
        
        
        user = new Utilisateurs(3, "mallek", "skander");
              if (current != null) {
            current.show();
            return;
        }
              
              
    //   new HomeFormSKA().show();
         
         
   //    new addadresse().show();
        //h.getF().show();
        
        
      // Panier s = new Panier(theme);
     // AddAdresse s = new AddAdresse(theme);
        
      Adreesse s = new Adreesse(theme);
      s.getF().show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
